name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        access_token_lifetime: 900s
        workload_identity_provider: 'projects/551624959543/locations/global/workloadIdentityPools/githubpool/providers/githubprovider'
        service_account: 'github-actions-sa@dryruns.iam.gserviceaccount.com'
        id_token_include_email: true

    - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: 'dryruns'
          export_default_credentials: true 

    - name: Run Cloud Build
      run: |
        gcloud builds submit --config cloudbuild.yaml  

    - name: Finish everything
      run: |
        echo "All done!"


    
    
        



