# Using https://github.com/google-github-actions/authname: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        access_token_lifetime: 900s
        workload_identity_provider: 'projects/551624959543/locations/global/workloadIdentityPools/github-int-pool/providers/github-provider'
        service_account: 'github-actions-sa@dryruns.iam.gserviceaccount.com'

    - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 444.0.0'
          project_id: '${{ env.PROJECT_ID }}'
        
      
    - name: 'Run Cloudbuild'
      run: |    
        gcloud builds submit --config cloudbuild.yaml 
    
    
        



