name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        access_token_lifetime: 900s
        workload_identity_provider: 'projects/551624959543/locations/global/workloadIdentityPools/github-int-pool/providers/github-int-provider'
        service_account: 'github-actions-sa@dryruns.iam.gserviceaccount.com'
        audience: 'https://token.actions.githubusercontent.com'

    - name: Print Identity Token
      run: |
        gcloud auth print-identity-token

    - name: Run Cloud Build
      run: |
        gcloud builds submit --config cloudbuild.yaml

    
    
        



