# Using https://github.com/google-github-actions/authname: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Authenticate to Google Cloud
      id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        access_token_lifetime: 900s
        workload_identity_provider: 'projects/551624959543/locations/global/workloadIdentityPools/github-int-pool/providers/github-provider'
        service_account: 'github-actions-sa@dryruns.iam.gserviceaccount.com'
        create_credentials_file: true
        activate_credentials_file: false       
        
    
    - name: 'Run Cloudbuild'
      run: |-
        gcloud auth login --brief --cred-file="${{ steps.auth-gcloud.outputs.credentials_file_path }}"
        gcloud builds submit --config cloudbuild.yaml 
    
    
        



